-- AlterTable
ALTER TABLE "Room" ALTER COLUMN "points" DROP NOT NULL,
ALTER COLUMN "points" DROP DEFAULT,
ALTER COLUMN "points" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Task" ALTER COLUMN "points" DROP NOT NULL,
ALTER COLUMN "points" DROP DEFAULT,
ALTER COLUMN "points" SET DATA TYPE TEXT;
